# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7214dbabc6e271751d67cfdf8babb9e9f437feabec282921083a7658917aea3568306a607cca12d0005ae5cf25db1d93280ecd6ab320dd7d6c7537b0fc4e4b36

test:
  secret_key_base: 5eaa5e3b36e30a3b3d6a5e95e91ef812e1b7bc75ba6ac487c897bece0408d7d936935ed2ba6d169b226ac9773e6d68a6e5863cdacd766096b0adab069528354c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
